routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FrontController@index')->name('home');
Route::get('/shirts','FrontController@shirts')->name('shirts');
Route::get('/shirt','FrontController@shirt')->name('shirt');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');  
Route::get('/home', 'HomeController@index');
Route::resource('/cart', 'CartController');
Route::get('/cart/add-items/{id}', 'CartController@addItem')->name('cart.addItem');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin'] ],function(){
    Route::post('toggledeliver/{orderId}', 'OrderController@toggledeliver')->name('toggle.deliver');

    Route::get('/',function(){
        return view('admin.index');
    })->name('admin.index');


    Route::resource('product','ProductsController');
    Route::resource('category','CategoriesController');
    Route::get('orders/{type?}','OrderController@Orders');
    
    
});
Route::resource('address','AddressController');
//Route::get('checkout','Checkout@step1');
Route::group(['middleware'=>'auth'], function(){

    Route::get('shipping-info','Checkout@shipping')->name('checkout.shipping');


});

Route::get('upload','AddressController@showForm');
Route::post('upload','AddressController@storecsv');


Route::get('csv_file', 'CsvFile@index');
Route::get('export', 'CsvFile@excel');


Route::post('csv_file/import', 'CsvFile@csv_import')->name('import');

//Route::get('checkout','Checkout@step1');

Route::get('payment','Checkout@payment')->name('checkout.payment');
Route::post('store-payment','Checkout@storePayment')->name('payment.store');

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Gloudemans\Shoppingcart\Facades\cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartItems=Cart::content();
        
      
        return view('cart.index',compact('cartItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    public function addItem($id){

        $product=Product::find($id);
        Cart::add($id,$product->name,1,$product->price,['size'=>'medium']);
        return back();

    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Cart::update($id,$request->qty);
        Cart::update($id,['qty'=>$request->qty]);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cart::remove($id);
        return back();
    }
}

resources/views/cart/index.blade.php
@extends('layout.main')

@section('content')

<div class="row">
    <h3>Cart Items</h3>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>qty</th>
                <th>size</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
        @foreach($cartItems as $cartItem)
            <tr>
                <td>{{$cartItem->name}}</td>
                <td>{{$cartItem->price}}</td>
                <td width="30px">
                    {{$cartItem->qty}}
                    {!! Form::open(['route'=>['cart.update', $cartItem->rowId],'method'=>'PUT']) !!}
                    <input name="qty" type="text" value="{{$cartItem->qty}}">
                    <input type="submit" class="btn btn-sm btn-default" value="Ok">
                    {!! Form::close() !!}
                </td>
                <td>{{$cartItem->options->has('size')?$cartItem->options->size:''}}</td>
                

                <td>


                <form action="{{route('cart.destroy',$cartItem->rowId)}}" method="POST">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                    <input class="button" type="submit" value="delete">
                    
                    





                </form>
                </td>

            </tr>
            @endforeach
            <tr>
                
                <td></td>
                <td>
                    subtotal : ${{Cart::subtotal()}}
                    
                    <br>
                    tax : ${{Cart::tax()}}
                    <br>
                    Grand Total : ${{Cart::total()}}
                </td>
                <td>Items : {{Cart::count()}}
                </td>
                <td></td>
                <td></td>

            </tr>
        </tbody>
    </table>
   


    <a href="{{route('checkout.shipping')}}" class="button">Check Out</a>
</div>
    @endsection