routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','FrontController@index')->name('home');
Route::get('/shirts','FrontController@shirts')->name('shirts');
Route::get('/shirt','FrontController@shirt')->name('shirt');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');  
Route::get('/home', 'HomeController@index');
Route::resource('/cart', 'CartController');
Route::get('/cart/add-items/{id}', 'CartController@addItem')->name('cart.addItem');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin'] ],function(){
    Route::post('toggledeliver/{orderId}', 'OrderController@toggledeliver')->name('toggle.deliver');

    Route::get('/',function(){
        return view('admin.index');
    })->name('admin.index');


    Route::resource('product','ProductsController');
    Route::resource('category','CategoriesController');
    Route::get('orders/{type?}','OrderController@Orders');
    
    
});
Route::resource('address','AddressController');
//Route::get('checkout','Checkout@step1');
Route::group(['middleware'=>'auth'], function(){

    Route::get('shipping-info','Checkout@shipping')->name('checkout.shipping');


});

Route::get('upload','AddressController@showForm');
Route::post('upload','AddressController@storecsv');


Route::get('csv_file', 'CsvFile@index');
Route::get('export', 'CsvFile@excel');


Route::post('csv_file/import', 'CsvFile@csv_import')->name('import');

//Route::get('checkout','Checkout@step1');

Route::get('payment','Checkout@payment')->name('checkout.payment');
Route::post('store-payment','Checkout@storePayment')->name('payment.store');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'description',
        'size',
        'price',
        'category_id',
        'image',

    ];


    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $products=Product::all();
       return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::pluck('name','id');
        return view('admin.product.create',compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $formInput=$request->except('image');
        //validation here
        $this->validate($request,[
            'name'=>'required',
            'price'=>'required',
            'size'=>'required',
            'image'=>'image|mimes:png,gif,jpg,jpeg|max:10000|required',
        ]);



        //image upload function here
        $image = $request->image;
        if($image){
            $imageName = $image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }



        Product::create($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $product = Product::find($id);
        
        return view('admin.product.edit',compact('product','id'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            
        ]);
        $product = Product::find($id);
        $product->name = $request->get('name');
        $product->save();
        return redirect()->route('product.index');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::where('id', $id)->delete();
        return redirect()->route('product.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.admin')

@section('content')


    <h3>Add Product</h3>
    <div class="row">

        <div class="col-md-6 col-md-offset-3">
                {!! Form::open(['route'=>'product.store','method'=>'post','files'=>true]) !!}
                <div class="form-group">
                    {{Form::label('name','Name')}}
                    {{Form::text('name',null,array('class','form-control'))}}
                </div>
                <div class="form-group">
                    {{Form::label('description','Description')}}
                    {{Form::text('description',null,array('class','form-control'))}}
                </div>
                <div class="form-group">
                        {{Form::label('price','Price')}}
                        {{Form::text('price',null,array('class','form-control'))}}
                    </div>
                <div class="form-group">
                    {{Form::label('size','Size')}}
                    {{Form::select('size',['small'=>'Small','medium'=>'Medium','large'=>'Large'],null,['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                        {{Form::label('category_id','Categories')}}
                        {{Form::select('category_id',$categories,null,['class'=>'form-control','placeholder'=>'select category'])}}
                    </div>
                <div class="form-group">
                    {{Form::label('image','Image')}}
                    {{Form::file('image',array('class','form-control'))}}
                </div>
                {{Form::submit('create',array('class'=>'btn btn-default'))}}
    
    
            {!! Form::close() !!}
    
    
        </div>

    </div>

    @endsection

resources/views/admin/product/csv_file_pagination.blade.php
@extends('admin.layout.admin')

@section('content')

<table class="table table-bordered table-striped">
 <thead>
  <tr>
   <th>Name</th>
   <th>Email Address</th>
  </tr>
 </thead>
 <tbody>
 @foreach($data as $row)
  <tr>
   <td>{{ $row->name }}</td>
   <td>{{ $row->email }}</td>
  </tr>
 @endforeach
 </tbody>
</table>

{!! $data->links() !!}
<form action="{{url('/export')}}" method="GET" enctype="multipart/form-data">
    {{csrf_field()}}
    <div class="form-group">
        <label for="upload-file">export users to csv</label>
        
    </div>
    <input class="btn btn-success" type="submit" value="export users table" name="submit">
</form>

@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout.admin')

@section('content');
div class="row">
 <div class="col-md-12">
  <br />
  <h3>Edit Record</h3>
  <br />
  @if(count($errors) > 0)

  <div class="alert alert-danger">
         <ul>
         @foreach($errors->all() as $error)
          <li>{{$error}}</li>
         @endforeach
         </ul>
  @endif
  <form method="post" action="{{action('ProductsController@update',$product['id'])}}">
   {{csrf_field()}}
   <input type="hidden" name="_method" value="PATCH" />
   <div class="form-group">
    <input type="text" name="name" class="form-control" value="{{$product->name}}" placeholder="Enter New Name" />
   </div>

   <div class="form-group">
    <input type="submit" class="btn btn-primary" value="Edit" />
   </div>
  </form>
 </div>
</div>

@endsection

resources/views/admin/product/excel.blade.php
<html>
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Laravel 5.8 - Import Export Data in CSV File</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 </head>
 <body>
  <div class="container">    
     <br />
     <h3 >Export Data in CSV File</h3>
     <br />
     <div class="panel panel-default">
          <div class="panel-heading">
           <h3 class="panel-title">Laravel 5.8 - Import Export Data in CSV File</h3>
          </div>
          <div class="panel-body">
           <form action="{{ route('import') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="file" name="file" accept=".csv">
                  <br>
                  <button class="btn btn-success">Import User Data</button>
                  <a class="btn btn-warning" href="{{ route('export') }}">Export User Data</a>
           </form>
              @yield('csv_data')
          </div>
      </div>
  </div>
 </body>
</html>

resources/views/admin/product/index.blade.php
@extends('admin.layout.admin')

@section('content')


    <h3>Products</h3>

    <ul>
        @forelse( $products as $product)
            

            <li>
                
                <div class="form-group">
                <a href="{{action('ProductsController@edit',$product['id'])}}">EDIT</a>
                </div>
                
                <h4>Name of product:{{$product->name}}</h4>
                <h4>Category:{{$product->category->name}}</h4>

            <form action="{{route('product.destroy',$product->id)}}" method="POST">
                {{csrf_field()}}
                {{method_field('DELETE')}}
                <input class="btn btn-sm btn-danger" type="submit" value="Delete">
            </form>
            
            {!! Form::close() !!}
            <br>
            




            </li>

           

        @empty
        <h3>No products</h3>

        @endforelse
        <li>
            <form action="{{url('/upload')}}" method="POST" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="upload-file">upload csv</label>
                    <input type="file" name="upload-file" class="form-control">
                </div>
                <input class="btn btn-success" type="submit" value="Upload Image" name="submit">
                 </form>

                <form action="{{url('/csv_file')}}" method="GET" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label for="upload-file">export users to csv</label>
                        
                    </div>
                    <input class="btn btn-success" type="submit" value="export users table" name="submit">
            </form>

            </li>

    </ul>


    @endsection